In [52]:
import pandas as pd

#nav_history Cleaning

In [53]:
dt_2=pd.read_csv('02_nav_history.csv')

In [54]:
print(dt_2.describe())
print(dt_2.info())

           amfi_code           nav
count   46000.000000  46000.000000
mean   120247.000000    269.570265
std     14352.317221    577.187060
min    100016.000000     26.136600
25%    118632.750000     69.170425
50%    119551.500000    122.732150
75%    120842.250000    260.338675
max    149324.000000   4268.549700
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB
None

In [55]:
#parse dates into datetime
dt_2.date=pd.to_datetime(dt_2.date)

In [56]:
dt_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[ns]
 2   nav        46000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 1.1 MB

In [57]:
#sort by amfi_code+date
dt_2=dt_2.sort_values(by=['amfi_code','date'])

In [58]:
#forward fill for missing nav
dt_2.nav=dt_2.groupby('amfi_code').nav.ffill()

In [59]:
#drop duplicates
dt_2=dt_2.drop_duplicates()

In [60]:
#Validate nav>0
dt_2=dt_2[dt_2.nav>0]

In [61]:
dt_2.to_csv('02_nav_history_cleaned.csv',index=False)

#scheme_performance cleaning

In [62]:
dt_7=pd.read_csv('07_scheme_performance.csv')

In [63]:
dt_7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [64]:
#Validate returns to numeric
returns=['return_1yr_pct','return_3yr_pct','return_5yr_pct']

for col in returns:
  dt_7[col]=pd.to_numeric(dt_7[col],errors='coerce')

In [65]:
dt_7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [66]:
#Flag anomalies
dt_7['anomaly']=dt_7[returns].isnull().any(axis=1)

In [67]:
#check expense ratio range
dt_7=dt_7[(dt_7.expense_ratio_pct>=0.1) & (dt_7.expense_ratio_pct<=2.5)]

In [68]:
dt_7.to_csv('07_scheme_performance_cleaned.csv',index=False)

#investor_transactions cleaning

In [69]:
dt_8=pd.read_csv('08_investor_transactions.csv')

In [70]:
dt_8.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [71]:
dt_8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  object
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 3.3+ MB

In [72]:
#Standardize transaction type
dt_8.transaction_type=dt_8.transaction_type.str.upper().str.strip()

In [100]:
dt_8=dt_8.rename(columns={'transaction_date':'date'})

In [74]:
#Validate amount
dt_8=dt_8[dt_8.amount_inr>0]

In [105]:
#Fix Date formats
dt_8.transaction=pd.to_datetime(dt_8.date,errors='coerce')

/tmp/ipykernel_1978/1004869080.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  dt_8.transaction=pd.to_datetime(dt_8.date,errors='coerce')

In [106]:
dt_8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   date                32778 non-null  datetime64[ns]
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(9)
memory usage: 3.3+ MB

In [107]:
#Validate KYC
valid_kyc=['Verified','Pending','Rejected']
dt_8=dt_8[dt_8.kyc_status.isin(valid_kyc)]

In [108]:
dt_8.to_csv('08_investor_transactions_cleaned.csv',index=False)

#Cleaning remaining datasets

In [79]:
dt_1=pd.read_csv('01_fund_master.csv')
dt_3=pd.read_csv('03_aum_by_fund_house.csv')
dt_4=pd.read_csv('04_monthly_sip_inflows.csv')
dt_5=pd.read_csv('05_category_inflows.csv')
dt_6=pd.read_csv('06_industry_folio_count.csv')
dt_9=pd.read_csv('09_portfolio_holdings.csv')
dt_10=pd.read_csv('10_benchmark_indices.csv')

In [80]:
dt_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_category       40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB

In [81]:
dt_1.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [109]:
dt_1=dt_1.rename(columns={'launch_date':'date'})

In [110]:
dt_1.date=pd.to_datetime(dt_1.date,errors='coerce')
dt_1.drop_duplicates()
dt_1.isna().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
date                  0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [111]:
dt_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   date                40 non-null     datetime64[ns]
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_category       40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(3), object(9)
memory usage: 4.8+ KB

In [84]:
dt_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     object
 1   fund_house      90 non-null     object
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.6+ KB

In [85]:
dt_3.date=pd.to_datetime(dt_3.date,errors='coerce')
dt_3.drop_duplicates()
dt_3.isna().sum()

date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

In [86]:
dt_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     object
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.4+ KB

In [112]:
dt_4=dt_4.rename(columns={'month':'date'})

In [113]:
dt_4.date=pd.to_datetime(dt_4.date,errors='coerce')
dt_4.drop_duplicates()
dt_4.isna().sum()

date                         0
sip_inflow_crore             0
active_sip_accounts_crore    0
new_sip_accounts_lakh        0
sip_aum_lakh_crore           0
yoy_growth_pct               0
dtype: int64

In [114]:
dt_4=dt_4.dropna()

In [115]:
dt_4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36 entries, 12 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   date                       36 non-null     datetime64[ns]
 1   sip_inflow_crore           36 non-null     int64
 2   active_sip_accounts_crore  36 non-null     float64
 3   new_sip_accounts_lakh      36 non-null     float64
 4   sip_aum_lakh_crore         36 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 2.0 KB

In [90]:
dt_4.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
12,2023-01-01,13856,6.13,9.10,5.82,20.31
13,2023-02-01,13687,6.19,8.20,5.88,19.66
14,2023-03-01,14276,6.32,10.00,6.01,15.80
15,2023-04-01,14749,6.41,9.25,6.15,24.33
16,2023-05-01,14749,6.50,8.70,6.22,20.05

In [91]:
dt_5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    object
 1   category          144 non-null    object
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), object(2)
memory usage: 3.5+ KB

In [116]:
dt_5=dt_5.rename(columns={'month':'date'})

In [118]:
dt_5.date=pd.to_datetime(dt_5.date,errors='coerce')
dt_5.drop_duplicates()
dt_5.isna().sum()

date                0
category            0
net_inflow_crore    0
dtype: int64

In [119]:
dt_6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     datetime64[ns]
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 1.1 KB

In [120]:
dt_6=dt_6.rename(columns={'month':'date'})

In [121]:
dt_6.date=pd.to_datetime(dt_6.date,errors='coerce')
dt_6.drop_duplicates()
dt_6.isna().sum()

date                   0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [122]:
dt_9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    object
 2   stock_name         322 non-null    object
 3   sector             322 non-null    object
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 20.3+ KB

In [123]:
dt_9=dt_9.rename(columns={'portfolio_date':'date'})

In [125]:
dt_9.date=pd.to_datetime(dt_9.date,errors='coerce')
dt_9.drop_duplicates()
dt_9.isna().sum()

amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
date                 0
dtype: int64

In [126]:
dt_10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   datetime64[ns]
 1   index_name   8050 non-null   object
 2   close_value  8050 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 188.8+ KB

In [98]:
dt_10.date=pd.to_datetime(dt_10.date,errors='coerce')
dt_10.drop_duplicates()
dt_10.isna().sum()

date           0
index_name     0
close_value    0
dtype: int64

In [127]:
dt_1.to_csv('01_fund_master_cleaned.csv',index=False)
dt_3.to_csv('03_aum_by_fund_house_cleaned.csv',index=False)
dt_4.to_csv('04_monthly_sip_inflows_cleaned.csv',index=False)
dt_5.to_csv('05_category_inflows_cleaned.csv',index=False)
dt_6.to_csv('06_industry_folio_count_cleaned.csv',index=False)
dt_9.to_csv('09_portfolio_holdings_cleaned.csv',index=False)
dt_10.to_csv('10_benchmark_indices_cleaned.csv',index=False)